import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        {/* site Favicon */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.css"
          precedence="default"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.theme.min.css"
          precedence="default"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
          precedence="default"
        ></link>
        <link
          rel="icon"
          href="assets/images/favicon/favicon.png"
          sizes="32x32"
        />
        <link
          rel="apple-touch-icon"
          href="assets/images/favicon/favicon.png"
          precedence="default"
        />
        <meta
          name="msapplication-TileImage"
          content="assets/images/favicon/favicon.png"
        />
        {/* css Icon Font */}
        <link
          rel="stylesheet"
          href="assets/css/vendor/ecicons.min.css"
          precedence="default"
        />
        {/* css All Plugins Files */}
        <link
          rel="stylesheet"
          href="assets/css/plugins/animate.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/plugins/swiper-bundle.min.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/plugins/jquery-ui.min.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/plugins/countdownTimer.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/plugins/slick.min.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/plugins/bootstrap.css"
          precedence="default"
        />
        {/* Main Style */}
        <link
          rel="stylesheet"
          href="assets/css/demo1.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/style.css"
          precedence="default"
        />
        <link
          rel="stylesheet"
          href="assets/css/responsive.css"
          precedence="default"
        />
        {/* Background css */}
        <link
          rel="stylesheet"
          id="bg-switcher-css"
          href="assets/css/backgrounds/bg-4.css"
          precedence="default"
        />

        {/* Header End  */}
        <body className={inter.className}>{children}</body>

        {/* Footer Start */}

        {/* <!-- Vendor JS --> */}

        <Script src="assets/js/vendor/jquery-3.5.1.min.js"></Script>
        <Script src="assets/js/vendor/popper.min.js"></Script>
        <Script src="assets/js/vendor/bootstrap.min.js"></Script>
        <Script src="assets/js/vendor/jquery-migrate-3.3.0.min.js"></Script>
        <Script src="assets/js/vendor/modernizr-3.11.2.min.js"></Script>
        {/* <!--Plugins JS--> */}
        <Script src="assets/js/plugins/swiper-bundle.min.js"></Script>
        <Script src="assets/js/plugins/countdownTimer.min.js"></Script>
        <Script src="assets/js/plugins/scrollup.js"></Script>
        <Script src="assets/js/plugins/jquery.zoom.min.js"></Script>
        <Script src="assets/js/plugins/slick.min.js"></Script>
        <Script src="assets/js/plugins/infiniteslidev2.js"></Script>
        <Script src="assets/js/vendor/jquery.magnific-popup.min.js"></Script>
        <Script src="assets/js/plugins/jquery.sticky-sidebar.js"></Script>
        {/* <!-- Google translate Js --> */}
        <Script src="assets/js/vendor/google-translate.js"></Script>

        {/* <!-- Main Js --> */}
        <Script src="assets/js/vendor/index.js"></Script>
        <Script src="assets/js/main.js"></Script>
        <Script src="assets/js/header.js"></Script>
        {/* <Script
          src="http://thecodeplayer.com/uploads/js/jquery-1.9.1.min.js"
          type="text/javascript"
        ></Script>
        <Script
          src="http://thecodeplayer.com/uploads/js/jquery.easing.min.js"
          type="text/javascript"
        ></Script> */}
        <Script
          type="text/javascript"
          src="https://code.jquery.com/jquery-1.12.0.min.js"
        ></Script>
        <Script
          type="text/javascript"
          src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js"
        ></Script>
      </html>
    </>
  );
}
